import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/client-layout";
import AuthProvider from "./providers/auth";
import localFont from 'next/font/local'
// import TopBar from "@/components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cabinet = localFont({
  src: [
    // { path: './fonts/CabinetGrotesk-Black.woff2', weight: '900', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Extrabold.woff2', weight: '800', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Bold.woff2', weight: '700', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Medium.woff2', weight: '500', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Light.woff2', weight: '300', style: 'normal' },
    { path: './fonts/CabinetGrotesk-Thin.woff2', weight: '200', style: 'normal' },
  ],
  variable: '--font-cabinet',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["next", "react", "typescript"],
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    type: "website",
  },
  twitter: {
    title: "Create Next App",
    description: "Generated by create next app",
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      > */}
      <body
        className={`${cabinet.variable} antialiased h-full`}
      >
        <AuthProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
